spring:
  datasource:
    url: jdbc:mysql://localhost:13306/mdm_code?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${DB_USER:mdm_code}
    password: ${DB_PASSWORD:spDHtT5ybBTT766c}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

cosid:
  enabled: true
